name: Check gene essentiality with Hart 2015

on:
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  check-metabolictasks:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run gene essentiality
        id: essentiality
        run: |
          TEST_RESULTS=$(/usr/local/bin/matlab -nodisplay -nosplash -nodesktop -r "ihuman = importYaml('Human-GEM.yml'); taskStruct = parseTaskList('data/metabolicTasks/metabolicTasks_Essential.txt'); eGenes = estimateEssentialGenes(ihuman, 'Hart2015_RNAseq.txt', taskStruct); disp(evaluateHart2015Essentiality(eGenes));" | awk 'NR>9 && !/^\.+/')
          PARSED_RESULTS="${TEST_RESULTS//'%'/'%25'}"
          PARSED_RESULTS="${PARSED_RESULTS//$'\n'/'<br>'}"
          PARSED_RESULTS="${PARSED_RESULTS//$'\r'/'<br>'}"
          echo "results=$PARSED_RESULTS" >> $GITHUB_OUTPUT

      - name: Post comment
        uses: NejcZdovc/comment-pr@v2
        with:
          file: "commentsFromTests.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TEST_RESULTS: ${{steps.essentiality.outputs.results}}
          GH_ACTION_RUN: ${{github.run_id}}
